{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gen.fullname" . }}
  labels:
    {{- include "gen.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
      port: {{ .Values.metrics.metric.port }}
      path: {{ .Values.metrics.metric.path }}
  selector:
    matchLabels:
      {{- include "gen.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/service: {{ .Values.metrics.service.name }}
{{- end }}
