{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gen.fullname" $ }}-{{ .name }}
  labels:
    {{- include "gen.labels" $ | nindent 4 }}
    app.kubernetes.io/service: {{ .name }}
spec:
  type: {{ .type | default "ClusterIP" }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: {{ .name }}
  selector:
    {{- include "gen.selectorLabels" $ | nindent 4 }}
{{- end }}
